on:
  push:
    branches:
      - main
    branches-ignore:
      - dev
name: Production Deploy1
jobs:
  web-deploy:
    name: FTP-Deploy-Action1
    runs-on: ubuntu-latest
    steps:
      - name: FTP-Deploy-Action1
        uses: actions/checkout@v2.1.0

      - name: FTP-Deploy-Action1
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.sepatil.in
          username: custombtp@sepatil.in
          password: ${{ secrets.FTP_CUSTOMBTP_PASSWORD }}
